const CHANNELS = {
  atmosphere: 0.55,
  structure: 0,
  process: 0,
  dryer: 0,
  interior: 0,
  product: 0,
  heat: 0,
  vapor: 0,
  sensors: 0,
  twin: 0,
  time: 0,
  preprocessing: 0,
  pipeline: 0,
  ridge: 0,
  novelty: 0,
  validation: 0,
  controlRoom: 0,
  roadmap: 0,
  visibility: 0
};

const world = (overrides) => ({ ...CHANNELS, ...overrides });
const env = (overrides = {}) => ({
  background: '#050b09',
  fog: '#07110e',
  fogDensity: 0.018,
  exposure: 1.02,
  key: 3.0,
  green: 28,
  warm: 15,
  blue: 8,
  ...overrides
});

export const scenes = [
  {
    id: 'site-awakening',
    eyebrow: 'OCP  /  SOLUBLE MAP',
    title: 'THE PROCESS NEVER WAITS.',
    subtitle: 'So visibility cannot either.',
    align: 'left-bottom wide',
    camera: { position: [27, 17, 34], target: [2, 2.1, 0], fov: 43, via: [0, 3, 2], roll: -0.012, drift: [0.34, 0.14, 0.24] },
    lens: { focus: 36, bloom: 0.58 },
    environment: env({ fogDensity: 0.013, key: 3.4, green: 22, warm: 9 }),
    transition: 0,
    hold: 5.8,
    world: world({ atmosphere: 0.72, structure: 0.9, process: 0.92, dryer: 0.86, product: 0.26 }),
    cue: 'Begin with the operating reality: the physical process evolves continuously. This project asks how supervision can remain readable between laboratory results.'
  },
  {
    id: 'follow-granule',
    eyebrow: '01  /  PROCESS JOURNEY',
    title: 'FOLLOW THE GRANULE.',
    subtitle: 'One product. Five coupled transformations.',
    align: 'left-top',
    camera: { position: [-25, 6.8, 13], target: [-7.5, 2.2, 0], fov: 47, via: [-3, -1, 5], roll: 0.008, drift: [0.26, 0.1, 0.16] },
    lens: { focus: 19, bloom: 0.86 },
    environment: env({ fogDensity: 0.02, green: 36, warm: 7 }),
    transition: 3.2,
    hold: 6.4,
    world: world({ atmosphere: 0.62, structure: 0.48, process: 1, dryer: 0.76, product: 1 }),
    labels: [
      { text: 'NEUTRALIZE', x: 18, y: 62 }, { text: 'CRYSTALLIZE', x: 34, y: 48 },
      { text: 'CENTRIFUGE', x: 50, y: 62 }, { text: 'DRY', x: 68, y: 47 }, { text: 'COOL', x: 83, y: 59 }
    ],
    cue: 'Follow the luminous MAP granule through neutralization, crystallization, centrifugation, drying, and cooling. Upstream history matters at the dryer.'
  },
  {
    id: 'dryer-hero',
    eyebrow: '02  /  HERO ASSET',
    title: 'THE DRYER DECIDES MOISTURE.',
    subtitle: 'Heat. Air. Feed. Residence.',
    align: 'left-top medium',
    camera: { position: [15.5, 6.8, 11.5], target: [6.5, 2.55, 0], fov: 36, via: [4, 2.5, -5], roll: -0.014, drift: [0.18, 0.12, 0.24] },
    lens: { focus: 11, bloom: 0.72 },
    environment: env({ fogDensity: 0.016, key: 3.8, green: 31, warm: 25 }),
    transition: 3.0,
    hold: 6.6,
    world: world({ atmosphere: 0.42, structure: 0.2, process: 0.55, dryer: 1, interior: 0.28, product: 0.62, heat: 0.72, vapor: 0.54 }),
    labels: [
      { text: 'WET FEED', x: 29, y: 56 }, { text: 'ROTARY DRUM', x: 58, y: 43 },
      { text: 'HOT AIR', x: 75, y: 58 }, { text: 'EXHAUST', x: 82, y: 34 }
    ],
    cue: 'Frame the dryer as the central transformation. The heat-and-mass-transfer visualization is explanatory and stylized, not a CFD claim.'
  },
  {
    id: 'inside-drum',
    eyebrow: '03  /  INSIDE THE DRUM',
    title: 'MOISTURE LEAVES IN MOTION.',
    subtitle: 'Rotation. Lift. Cascade. Evaporation.',
    align: 'right-top medium',
    camera: { position: [6.2, 3.2, 7.2], target: [6.5, 2.45, 0], fov: 42, via: [-2.5, -0.5, -1.5], roll: 0.018, drift: [0.1, 0.07, 0.16] },
    lens: { focus: 7.2, bloom: 1.08 },
    environment: env({ background: '#090b08', fog: '#090b08', fogDensity: 0.012, exposure: 1.1, key: 2.1, green: 16, warm: 42 }),
    transition: 2.8,
    hold: 6.8,
    world: world({ atmosphere: 0.2, structure: 0.05, process: 0.08, dryer: 0.2, interior: 1, product: 0.26, heat: 1, vapor: 1 }),
    detail: '<span class="microtag warm">SCHEMATIC MECHANISM</span>',
    cue: 'Show product lifting and cascading through a heat gradient while vapor leaves. State that this is a conceptual mechanism used to explain residence-aware data preparation.'
  },
  {
    id: 'time-tunnel',
    eyebrow: '04  /  THE VISIBILITY GAP',
    title: 'TWO HOURS OF SILENCE.',
    subtitle: 'The process keeps writing its story.',
    align: 'left-top medium',
    camera: { position: [6.5, 4.3, 8], target: [6.5, 2.0, -14], fov: 44, via: [0, 4, -5], roll: -0.01, drift: [0.08, 0.05, 0.2] },
    lens: { focus: 20, bloom: 1.0 },
    environment: env({ background: '#040907', fogDensity: 0.014, key: 2.4, green: 40, warm: 13 }),
    transition: 3.4,
    hold: 7.2,
    world: world({ atmosphere: 0.28, dryer: 0.16, interior: 0.1, product: 0.18, time: 1, visibility: 0.35 }),
    detail: '<span class="metric-chip"><b>LAB</b> ~ 2 h</span><span class="metric-chip accent"><b>REPLAY</b> dt = 5 s</span>',
    cue: 'Laboratory moisture remains the quality reference and is available approximately every two hours. The dense five-second rhythm is prototype replay and visualization only, not a confirmed historian frequency.'
  },
  {
    id: 'signal-lattice',
    eyebrow: '05  /  PREPROCESSING',
    title: 'SIGNALS BECOME STRUCTURE.',
    subtitle: 'Align. Clean. Engineer. Replay.',
    align: 'left-top medium',
    camera: { position: [13.5, 7.2, 6.5], target: [5.2, 2.7, -11.5], fov: 45, via: [4, 1, -3], roll: 0.014, drift: [0.16, 0.08, 0.14] },
    lens: { focus: 18, bloom: 0.82 },
    environment: env({ fogDensity: 0.018, key: 3, green: 34, blue: 22 }),
    transition: 3.2,
    hold: 6.2,
    world: world({ atmosphere: 0.42, structure: 0.08, process: 0.16, dryer: 0.5, sensors: 1, twin: 0.8, time: 0.18, preprocessing: 1, pipeline: 0.22 }),
    labels: [
      { text: 'ALIGN', x: 53, y: 40 }, { text: 'CLEAN', x: 62, y: 50 },
      { text: 'ENGINEER', x: 71, y: 40 }, { text: 'REPLAY', x: 80, y: 50 }
    ],
    cue: 'The first digitalization act is disciplined data preparation. Process signals are aligned, cleaned, enriched with engineering relationships, and replayed reproducibly.'
  },
  {
    id: 'architecture-flight',
    eyebrow: '06  /  END-TO-END ARCHITECTURE',
    title: 'ONE PIPELINE. FIVE LAYERS.',
    subtitle: 'Sensors -> Python -> models -> PostgreSQL -> Power BI',
    align: 'left-top wide',
    camera: { position: [16.2, 8.0, -4.5], target: [3.0, 2.5, -29], fov: 48, via: [-2, 2.4, -5], roll: -0.014, drift: [0.16, 0.09, 0.2] },
    lens: { focus: 23, bloom: 0.9 },
    environment: env({ fogDensity: 0.014, key: 2.7, green: 35, blue: 28 }),
    transition: 3.6,
    hold: 7.0,
    world: world({ atmosphere: 0.36, dryer: 0.12, sensors: 0.34, twin: 0.12, preprocessing: 0.12, pipeline: 1, ridge: 0.18, novelty: 0.18, controlRoom: 0.04 }),
    cue: 'Follow the data path in depth. Python performs preprocessing and model inference. PostgreSQL persists operational outputs. Power BI visualizes those outputs; it does not run either model.'
  },
  {
    id: 'intelligence-split',
    eyebrow: '07  /  MODEL INTELLIGENCE',
    title: 'TWO QUESTIONS. TWO BRANCHES.',
    subtitle: 'Moisture now?  /  Process different?',
    align: 'center-top',
    camera: { position: [3.2, 7.6, -15], target: [3.2, 2.8, -27.5], fov: 46, via: [0, 2.2, -1], roll: 0, drift: [0.18, 0.07, 0.12] },
    lens: { focus: 13, bloom: 1.02 },
    environment: env({ background: '#040a09', fogDensity: 0.011, key: 2.4, green: 38, warm: 17, blue: 28 }),
    transition: 3.0,
    hold: 5.8,
    world: world({ atmosphere: 0.3, preprocessing: 0.18, pipeline: 0.76, ridge: 0.82, novelty: 0.82 }),
    detail: '<span class="branch-chip ridge">RIDGE / QUALITY</span><span class="branch-chip svm">ONE-CLASS SVM / PROCESS</span>',
    cue: 'Separate the two tasks clearly. Ridge estimates quality between laboratory anchors. One-Class SVM identifies process novelty without using the quality target.'
  },
  {
    id: 'ridge-ribbon',
    eyebrow: '08  /  QUALITY BRANCH',
    title: 'RIDGE ESTIMATES BETWEEN LABS.',
    subtitle: 'alpha = 10. 16 features. Advisory only.',
    align: 'left-top medium',
    camera: { position: [-5.2, 4.8, -20], target: [-7.2, 2.5, -30], fov: 40, via: [-2.5, 1, -2], roll: -0.016, drift: [0.15, 0.08, 0.14] },
    lens: { focus: 10.5, bloom: 1.04 },
    environment: env({ background: '#04100a', fogDensity: 0.013, key: 2.6, green: 42, warm: 4, blue: 12 }),
    transition: 3.0,
    hold: 7.0,
    world: world({ atmosphere: 0.26, pipeline: 0.34, ridge: 1, novelty: 0.08, validation: 0.08 }),
    detail: '<span class="microtag">LAB REMAINS THE REFERENCE</span>',
    cue: 'Ridge uses sixteen current, historical, and engineered features. Its purpose is an advisory estimate between lab measurements; it does not replace laboratory moisture.'
  },
  {
    id: 'novelty-envelope',
    eyebrow: '09  /  PROCESS BRANCH',
    title: 'THE SVM RECOGNIZES NOVELTY.',
    subtitle: '15 process-only features. Evidence, not causality.',
    align: 'right-top medium',
    camera: { position: [12.8, 5.4, -20], target: [12.4, 2.7, -30], fov: 40, via: [4, 0.8, -1.5], roll: 0.016, drift: [0.16, 0.09, 0.13] },
    lens: { focus: 10.5, bloom: 0.98 },
    environment: env({ background: '#090b08', fogDensity: 0.013, key: 2.5, green: 28, warm: 31, blue: 12 }),
    transition: 3.2,
    hold: 7.0,
    world: world({ atmosphere: 0.26, pipeline: 0.34, ridge: 0.08, novelty: 1, validation: 0.06 }),
    detail: '<span class="metric-chip accent"><b>5.925%</b> validation flags</span><span class="microtag warm">RISK != PROBABILITY</span>',
    cue: 'A negative decision function indicates novelty. The displayed risk is a transform, not a probability. Ranked contributors localize evidence for verification; they do not establish cause.'
  },
  {
    id: 'validation-theatre',
    eyebrow: '10  /  HELD-OUT EVIDENCE',
    title: 'EVIDENCE BEFORE AMBITION.',
    subtitle: 'Synthetic prototype. Chronological test. Advisory only.',
    align: 'left-top compact',
    camera: { position: [3.2, 5.5, -31.5], target: [3.2, 3.2, -40], fov: 38, via: [-2, 1.5, -2], roll: -0.006, drift: [0.08, 0.05, 0.12] },
    lens: { focus: 9.2, bloom: 0.48 },
    environment: env({ background: '#0d110e', fog: '#0d110e', fogDensity: 0.009, exposure: 1.12, key: 4.2, green: 20, warm: 5, blue: 9 }),
    transition: 3.2,
    hold: 8.4,
    world: world({ atmosphere: 0.18, pipeline: 0.025, ridge: 0.1, novelty: 0.025, validation: 1 }),
    detail: '<div class="metrics"><span><i>R2</i><b>0.8245</b></span><span><i>MAE</i><b>0.001069</b></span><span><i>RMSE</i><b>0.001403</b></span></div><small>TEST / 165 LAB SAMPLES / ERROR UNITS: PERCENTAGE POINTS % H2O</small>',
    cue: 'Read the chronological TEST metrics honestly. The deterministic 92-day synthetic dataset supports reproducibility, not proof of live plant generalization.'
  },
  {
    id: 'control-room',
    eyebrow: '11  /  OPERATOR SUPERVISION',
    title: 'SUPERVISION, NOT AUTOMATION.',
    subtitle: 'Power BI visualizes. Python runs models.',
    align: 'left-top compact',
    camera: { position: [3.2, 4.7, -41.5], target: [3.2, 3.0, -52], fov: 40, via: [2.5, 0.6, -2], roll: 0.008, drift: [0.12, 0.04, 0.13] },
    lens: { focus: 11.2, bloom: 0.66 },
    environment: env({ background: '#030807', fogDensity: 0.008, exposure: 1.05, key: 2.2, green: 29, warm: 5, blue: 31 }),
    transition: 3.4,
    hold: 8.2,
    world: world({ atmosphere: 0.18, pipeline: 0.055, validation: 0.06, controlRoom: 1 }),
    detail: '<span class="microtag">AUTHENTIC PROJECT PREVIEWS</span><span class="microtag">NO MODEL EXECUTION IN POWER BI</span>',
    cue: 'Treat the dashboard as a control-room surface, not another model. The two authentic project pages support overview and investigation. Power BI only visualizes database outputs.'
  },
  {
    id: 'operating-loop',
    eyebrow: '12  /  SYSTEM IN MOTION',
    title: 'ONE OPERATING INTELLIGENCE LOOP.',
    subtitle: 'Replay -> predict -> detect -> publish -> supervise',
    align: 'left-top wide',
    camera: { position: [23, 13, 24], target: [3.5, 2.1, -14], fov: 52, via: [0, 12, 8], roll: -0.02, drift: [0.38, 0.13, 0.25] },
    lens: { focus: 43, bloom: 0.82 },
    environment: env({ fogDensity: 0.012, exposure: 1.04, key: 3.3, green: 35, warm: 15, blue: 16 }),
    transition: 4.2,
    hold: 7.2,
    world: world({ atmosphere: 0.66, structure: 0.42, process: 0.66, dryer: 0.82, product: 0.6, heat: 0.28, vapor: 0.24, sensors: 0.68, twin: 0.48, time: 0.24, preprocessing: 0.52, pipeline: 0.86, ridge: 0.5, novelty: 0.5, validation: 0.12, controlRoom: 0.5, visibility: 0.62 }),
    detail: '<span class="metric-chip accent"><b>5 s</b> prototype replay</span><span class="microtag">ADVISORY / NO WRITE-BACK</span>',
    cue: 'Reassemble the complete runtime logic. Five seconds is the prototype replay and visualization cadence. There is no live PCS7 connection, actuator write-back, or autonomous control.'
  },
  {
    id: 'governed-roadmap',
    eyebrow: '13  /  GOVERNED SCALE-UP',
    title: 'PROVE IT IN SHADOW MODE.',
    subtitle: 'Read-only plant data -> validation -> governed advisory',
    align: 'left-top wide',
    camera: { position: [11.8, 6.8, -50.5], target: [3.0, 2.5, -65.5], fov: 44, via: [-2.5, 2.6, -2.5], roll: 0.008, drift: [0.15, 0.07, 0.17] },
    lens: { focus: 15.5, bloom: 0.76 },
    environment: env({ background: '#050a08', fogDensity: 0.012, key: 2.7, green: 37, warm: 8, blue: 18 }),
    transition: 3.6,
    hold: 7.4,
    world: world({ atmosphere: 0.34, pipeline: 0.1, controlRoom: 0.035, roadmap: 1, visibility: 0.2 }),
    detail: '<span class="microtag">NO LIVE PCS7</span><span class="microtag">NO CLOSED LOOP</span>',
    cue: 'The next step is read-only plant data, data-quality review, and shadow validation against laboratory results and operator observation. Governed advisory comes only after evidence.'
  },
  {
    id: 'closing-visibility',
    eyebrow: 'SOLUBLE MAP  /  DRYER DIGITALIZATION',
    title: 'THE DRYER KEEPS MOVING.',
    subtitle: 'Digital visibility continues beyond laboratory delay.',
    align: 'left-bottom wide closing',
    camera: { position: [15.5, 10.5, 23], target: [6.5, 2.35, 0], fov: 39, via: [12, 20, 18], roll: -0.014, drift: [0.28, 0.12, 0.2] },
    lens: { focus: 27, bloom: 0.94 },
    environment: env({ background: '#030806', fogDensity: 0.012, key: 3.6, green: 38, warm: 18, blue: 10 }),
    transition: 5.0,
    hold: 12,
    world: world({ atmosphere: 0.74, structure: 0.62, process: 0.8, dryer: 1, interior: 0.24, product: 0.44, heat: 0.38, vapor: 0.38, sensors: 0.7, twin: 0.8, time: 0.32, preprocessing: 0.18, pipeline: 0.28, ridge: 0.12, novelty: 0.12, controlRoom: 0.12, visibility: 1 }),
    detail: '<span class="microtag">LABORATORY MOISTURE REMAINS THE REFERENCE</span>',
    cue: 'Return to the still-rotating dryer. Close on continuous visibility with human verification intact, then invite questions.'
  }
];
